import { Question } from '../types'

export const QUESTIONS: Question[] = [
  // ========== ARRAYS (gear: wooden_sword, forest_boots) ==========
  {
    id: 'arr_1',
    title: 'Two Sum',
    description: 'Given an array [2,7,11,15] and target=9, what is the time complexity of the optimal solution using a hashmap?',
    difficulty: 'easy',
    category: 'arrays',
    gearReward: 'wooden_sword',
    timeLimit: 45,
    choices: { a: 'O(n²)', b: 'O(n log n)', c: 'O(n)', d: 'O(log n)' },
    correctAnswer: 'c',
    explanation: 'Using a hashmap, we iterate once storing complements. Each lookup is O(1), giving us O(n) overall.',
    leetcodeUrl: 'https://leetcode.com/problems/two-sum/',
  },
  {
    id: 'arr_2',
    title: 'Best Time to Buy and Sell Stock',
    description: 'In array [7,1,5,3,6,4], what\'s the maximum profit from one buy-sell transaction?',
    difficulty: 'easy',
    category: 'arrays',
    gearReward: 'wooden_sword',
    timeLimit: 45,
    choices: { a: '5', b: '6', c: '7', d: '3' },
    correctAnswer: 'a',
    explanation: 'Buy at 1, sell at 6. Profit = 6 - 1 = 5. Track min price and max profit in one pass.',
    leetcodeUrl: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
  },
  {
    id: 'arr_3',
    title: 'Contains Duplicate',
    description: 'What is the MOST efficient approach to check if array [1,2,3,1] has duplicates?',
    difficulty: 'easy',
    category: 'arrays',
    gearReward: 'forest_boots',
    timeLimit: 30,
    choices: { a: 'Sort and check neighbors — O(n log n)', b: 'Nested loops — O(n²)', c: 'HashSet — O(n) time, O(n) space', d: 'Binary search — O(n log n)' },
    correctAnswer: 'c',
    explanation: 'Add elements to a Set. If Set.size < array.length, we have duplicates. O(n) time.',
    leetcodeUrl: 'https://leetcode.com/problems/contains-duplicate/',
  },
  {
    id: 'arr_4',
    title: 'Maximum Subarray',
    description: 'Kadane\'s Algorithm finds the max subarray sum in O(n). For array [-2,1,-3,4,-1,2,1,-5,4], what is the max sum?',
    difficulty: 'easy',
    category: 'arrays',
    gearReward: 'wooden_sword',
    timeLimit: 60,
    choices: { a: '5', b: '6', c: '4', d: '7' },
    correctAnswer: 'b',
    explanation: 'Subarray [4,-1,2,1] has sum 6. Kadane\'s: track currentMax and globalMax, reset when sum goes negative.',
    leetcodeUrl: 'https://leetcode.com/problems/maximum-subarray/',
  },
  {
    id: 'arr_5',
    title: 'Product of Array Except Self',
    description: 'For array [1,2,3,4], product except self is [24,12,8,6]. What technique avoids using division?',
    difficulty: 'medium',
    category: 'arrays',
    gearReward: 'forest_boots',
    timeLimit: 60,
    choices: { a: 'Use division: totalProduct / arr[i]', b: 'Prefix products array and suffix products array', c: 'Nested loop multiply all others', d: 'Binary search for each element' },
    correctAnswer: 'b',
    explanation: 'Compute prefix products left-to-right, suffix products right-to-left. Multiply them at each index.',
    leetcodeUrl: 'https://leetcode.com/problems/product-of-array-except-self/',
  },

  // ========== STRINGS (gear: leather_armor) ==========
  {
    id: 'str_1',
    title: 'Valid Anagram',
    description: 'To check if "anagram" and "nagaram" are anagrams, which approach is O(n) time and O(1) space?',
    difficulty: 'easy',
    category: 'strings',
    gearReward: 'leather_armor',
    timeLimit: 45,
    choices: { a: 'Sort both strings and compare', b: 'Count char frequencies using a 26-element array', c: 'Check if they contain the same characters', d: 'Use regex matching' },
    correctAnswer: 'b',
    explanation: 'Count chars in first string (increment), count in second (decrement). If all zeros, they\'re anagrams.',
    leetcodeUrl: 'https://leetcode.com/problems/valid-anagram/',
  },
  {
    id: 'str_2',
    title: 'Valid Palindrome',
    description: 'What is the space complexity of checking palindrome "A man a plan a canal Panama" using two pointers?',
    difficulty: 'easy',
    category: 'strings',
    gearReward: 'leather_armor',
    timeLimit: 30,
    choices: { a: 'O(n) — need to store cleaned string', b: 'O(1) — just two pointer variables', c: 'O(n²) — nested comparison', d: 'O(log n)' },
    correctAnswer: 'b',
    explanation: 'Two pointers (left, right) approach uses O(1) extra space. Skip non-alphanumeric chars in place.',
    leetcodeUrl: 'https://leetcode.com/problems/valid-palindrome/',
  },
  {
    id: 'str_3',
    title: 'Longest Common Prefix',
    description: 'For strings ["flower","flow","flight"], the longest common prefix is?',
    difficulty: 'easy',
    category: 'strings',
    gearReward: 'leather_armor',
    timeLimit: 30,
    choices: { a: '"flow"', b: '"fl"', c: '"f"', d: '""' },
    correctAnswer: 'b',
    explanation: '"fl" is the longest prefix shared by all three strings. Vertical scan: compare character by character.',
    leetcodeUrl: 'https://leetcode.com/problems/longest-common-prefix/',
  },
  {
    id: 'str_4',
    title: 'Reverse Words in String',
    description: 'What\'s the most elegant way to reverse words in "  hello world  "?',
    difficulty: 'medium',
    category: 'strings',
    gearReward: 'leather_armor',
    timeLimit: 45,
    choices: { a: 'Split on spaces, filter empty, reverse, join', b: 'Use two pointers on character level', c: 'Iterate and find word boundaries', d: 'Stack-based approach' },
    correctAnswer: 'a',
    explanation: 'Split by whitespace (handles multiple spaces), filter empty strings, reverse array, join with single space.',
    leetcodeUrl: 'https://leetcode.com/problems/reverse-words-in-a-string/',
  },

  // ========== HASH MAPS (gear: hash_shield) ==========
  {
    id: 'hash_1',
    title: 'Group Anagrams',
    description: 'To group ["eat","tea","tan","ate","nat","bat"], what key should we use in a HashMap?',
    difficulty: 'medium',
    category: 'hashmaps',
    gearReward: 'hash_shield',
    timeLimit: 60,
    choices: { a: 'First character of each word', b: 'Sorted version of each word', c: 'Length of each word', d: 'Character count as array of 26' },
    correctAnswer: 'b',
    explanation: 'Sorting "eat" and "tea" both give "aet". Both b and d work, but sorting is the classic elegant solution.',
    leetcodeUrl: 'https://leetcode.com/problems/group-anagrams/',
  },
  {
    id: 'hash_2',
    title: 'Top K Frequent Elements',
    description: 'For [1,1,1,2,2,3] with k=2, what combination gives O(n) time complexity?',
    difficulty: 'medium',
    category: 'hashmaps',
    gearReward: 'hash_shield',
    timeLimit: 60,
    choices: { a: 'HashMap + sort by frequency O(n log n)', b: 'HashMap + min-heap of size k O(n log k)', c: 'HashMap + bucket sort by frequency O(n)', d: 'Pure sorting approach O(n log n)' },
    correctAnswer: 'c',
    explanation: 'Bucket sort: create buckets[i] = list of numbers with frequency i. Buckets array size = n. O(n) total.',
    leetcodeUrl: 'https://leetcode.com/problems/top-k-frequent-elements/',
  },

  // ========== TWO POINTERS (gear: iron_dagger) ==========
  {
    id: 'tp_1',
    title: 'Three Sum',
    description: 'For array [-1,0,1,2,-1,-4] find all triplets summing to 0. What\'s the optimal time complexity?',
    difficulty: 'medium',
    category: 'twopointers',
    gearReward: 'iron_dagger',
    timeLimit: 60,
    choices: { a: 'O(n³) — three nested loops', b: 'O(n²) — sort + outer loop + two pointers', c: 'O(n log n) — sort + binary search', d: 'O(n) — hashmap based' },
    correctAnswer: 'b',
    explanation: 'Sort array O(n log n). For each i, use two pointers on remaining subarray O(n). Total: O(n²).',
    leetcodeUrl: 'https://leetcode.com/problems/3sum/',
  },
  {
    id: 'tp_2',
    title: 'Container With Most Water',
    description: 'Given heights [1,8,6,2,5,4,8,3,7], max water = 49. Why does greedy two-pointer work?',
    difficulty: 'medium',
    category: 'twopointers',
    gearReward: 'iron_dagger',
    timeLimit: 60,
    choices: { a: 'Moving the taller pointer can never increase area', b: 'Moving the shorter pointer might find a taller boundary', c: 'Both pointers must always move inward', d: 'Random movement guarantees optimal' },
    correctAnswer: 'b',
    explanation: 'Width decreases when we move inward. Only chance to increase area is to find taller heights — so move the shorter pointer.',
    leetcodeUrl: 'https://leetcode.com/problems/container-with-most-water/',
  },

  // ========== SLIDING WINDOW (gear: desert_helm) ==========
  {
    id: 'sw_1',
    title: 'Longest Substring Without Repeating Characters',
    description: 'For "abcabcbb", the longest non-repeating substring is? Which algorithm finds it in O(n)?',
    difficulty: 'medium',
    category: 'slidingwindow',
    gearReward: 'desert_helm',
    timeLimit: 60,
    choices: { a: '"abc" (3) — sliding window + hashmap', b: '"abcabc" (6) — two pointers', c: '"abcabcb" (7) — brute force', d: '"b" (1) — wrong tracking' },
    correctAnswer: 'a',
    explanation: '"abc" has length 3. Use sliding window: expand right, when duplicate found, shrink left to remove duplicate.',
    leetcodeUrl: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
  },
  {
    id: 'sw_2',
    title: 'Minimum Window Substring',
    description: 'In string "ADOBECODEBANC" find minimum window containing "ABC". What space complexity does sliding window need?',
    difficulty: 'hard',
    category: 'slidingwindow',
    gearReward: 'desert_helm',
    timeLimit: 90,
    choices: { a: 'O(1) — just two pointers', b: 'O(|t|) — frequency map of target', c: 'O(|s|) — frequency map of string', d: 'O(|s| + |t|) — maps for both' },
    correctAnswer: 'b',
    explanation: 'We need a frequency map for target t. The window is just indices into s. Answer is "BANC".',
    leetcodeUrl: 'https://leetcode.com/problems/minimum-window-substring/',
  },

  // ========== BINARY SEARCH (gear: silver_bow) ==========
  {
    id: 'bs_1',
    title: 'Binary Search',
    description: 'Searching for 9 in [-1,0,3,5,9,12]. Binary search returns index 4. What is the key invariant?',
    difficulty: 'easy',
    category: 'binarysearch',
    gearReward: 'silver_bow',
    timeLimit: 45,
    choices: { a: 'Always move left pointer to mid+1 and right pointer to mid-1', b: 'Maintain: left <= right, target is always in [left, right]', c: 'Always check the middle element first', d: 'Move both pointers after each comparison' },
    correctAnswer: 'b',
    explanation: 'The invariant: if target exists, it must be in [left, right]. When mid != target, safely eliminate half the search space.',
    leetcodeUrl: 'https://leetcode.com/problems/binary-search/',
  },
  {
    id: 'bs_2',
    title: 'Find Minimum in Rotated Sorted Array',
    description: 'Array [3,4,5,1,2] is rotated. Binary search finds minimum at index 3. The key decision at each step?',
    difficulty: 'medium',
    category: 'binarysearch',
    gearReward: 'silver_bow',
    timeLimit: 60,
    choices: { a: 'If mid > right, minimum is in right half', b: 'If mid < left, minimum is in left half', c: 'Always pick the smaller of left/right', d: 'The minimum is always at index n/2' },
    correctAnswer: 'a',
    explanation: 'If arr[mid] > arr[right], the pivot (minimum) must be in the right half. Otherwise it\'s in left half.',
    leetcodeUrl: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/',
  },
  {
    id: 'bs_3',
    title: 'Search in Rotated Sorted Array',
    description: 'For [4,5,6,7,0,1,2] target=0, binary search finds index 4. At each step, how do we know which half is sorted?',
    difficulty: 'medium',
    category: 'binarysearch',
    gearReward: 'silver_bow',
    timeLimit: 60,
    choices: { a: 'The half with smaller sum is sorted', b: 'Compare arr[left] with arr[mid] — if arr[left] <= arr[mid], left half is sorted', c: 'The left half is always sorted', d: 'Compare arr[mid] with arr[right]' },
    correctAnswer: 'b',
    explanation: 'If arr[left] <= arr[mid], left half is sorted. Then check if target is in sorted range; if not, search right.',
    leetcodeUrl: 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
  },

  // ========== LINKED LIST (gear: chain_whip) ==========
  {
    id: 'll_1',
    title: 'Reverse Linked List',
    description: 'To reverse 1->2->3->4->5 iteratively, how many pointer variables do we need?',
    difficulty: 'easy',
    category: 'linkedlist',
    gearReward: 'chain_whip',
    timeLimit: 45,
    choices: { a: 'One: just track current', b: 'Two: current and next', c: 'Three: prev, current, next', d: 'Four: we need extra space' },
    correctAnswer: 'c',
    explanation: 'We need prev (starts null), curr (starts head), and next (temp storage). Classic 3-pointer reversal.',
    leetcodeUrl: 'https://leetcode.com/problems/reverse-linked-list/',
  },
  {
    id: 'll_2',
    title: 'Linked List Cycle',
    description: 'Floyd\'s cycle detection uses slow and fast pointers. If there is a cycle, when do they meet?',
    difficulty: 'easy',
    category: 'linkedlist',
    gearReward: 'chain_whip',
    timeLimit: 45,
    choices: { a: 'They meet at the cycle entry point', b: 'They always meet at the head', c: 'They meet somewhere inside the cycle', d: 'They never meet in a valid cycle' },
    correctAnswer: 'c',
    explanation: 'Fast pointer moves 2x, slow 1x. They will meet somewhere inside the cycle (not necessarily entry). O(1) space.',
    leetcodeUrl: 'https://leetcode.com/problems/linked-list-cycle/',
  },
  {
    id: 'll_3',
    title: 'Merge Two Sorted Lists',
    description: 'Merging [1,2,4] and [1,3,4], what technique avoids allocating extra nodes?',
    difficulty: 'easy',
    category: 'linkedlist',
    gearReward: 'chain_whip',
    timeLimit: 45,
    choices: { a: 'Copy both lists to array and merge', b: 'Use a dummy head node and rewire existing nodes', c: 'Create all new nodes for the result', d: 'Recursion always creates new nodes' },
    correctAnswer: 'b',
    explanation: 'Use a dummy head, then choose the smaller node between l1 and l2, advancing that pointer. Rewires in O(n+m).',
    leetcodeUrl: 'https://leetcode.com/problems/merge-two-sorted-lists/',
  },
  {
    id: 'll_4',
    title: 'Remove Nth Node From End',
    description: 'Removing 2nd from end of [1,2,3,4,5] gives [1,2,3,5]. One-pass O(n) approach uses?',
    difficulty: 'medium',
    category: 'linkedlist',
    gearReward: 'chain_whip',
    timeLimit: 60,
    choices: { a: 'Two passes: first count length, second remove', b: 'Two pointers separated by n+1 nodes', c: 'Recursive backtracking to count from end', d: 'Stack to store all nodes' },
    correctAnswer: 'b',
    explanation: 'Move fast pointer n+1 steps ahead. Then move both until fast reaches null. Slow is now at the node before target.',
    leetcodeUrl: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',
  },

  // ========== TREES (gear: tree_staff, ice_gauntlets, crystal_armor) ==========
  {
    id: 'tree_1',
    title: 'Invert Binary Tree',
    description: 'To invert a binary tree (swap all left/right children), which traversal approach works cleanly?',
    difficulty: 'easy',
    category: 'trees',
    gearReward: 'tree_staff',
    timeLimit: 45,
    choices: { a: 'Only BFS works for tree inversion', b: 'Both DFS (recursive/iterative) and BFS work', c: 'Inorder traversal is the only correct approach', d: 'You must use a stack-based DFS only' },
    correctAnswer: 'b',
    explanation: 'Recursive DFS: swap children, recurse on both. BFS: swap children for each node as we visit it. Both work!',
    leetcodeUrl: 'https://leetcode.com/problems/invert-binary-tree/',
  },
  {
    id: 'tree_2',
    title: 'Maximum Depth of Binary Tree',
    description: 'What is the maximum depth of a complete binary tree with 7 nodes?',
    difficulty: 'easy',
    category: 'trees',
    gearReward: 'tree_staff',
    timeLimit: 30,
    choices: { a: '7', b: '4', c: '3', d: '2' },
    correctAnswer: 'c',
    explanation: 'A complete binary tree with 7 nodes has 3 levels (root, 2 children, 4 grandchildren). Height = 3.',
    leetcodeUrl: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/',
  },
  {
    id: 'tree_3',
    title: 'Level Order Traversal',
    description: 'BFS level-order traversal uses which data structure to process nodes level by level?',
    difficulty: 'medium',
    category: 'trees',
    gearReward: 'ice_gauntlets',
    timeLimit: 45,
    choices: { a: 'Stack (LIFO) for DFS by level', b: 'Queue (FIFO) for BFS', c: 'Priority Queue for sorted levels', d: 'Deque for bidirectional traversal' },
    correctAnswer: 'b',
    explanation: 'BFS uses a Queue. Add root, then for each level: record current queue size, dequeue all, add their children.',
    leetcodeUrl: 'https://leetcode.com/problems/binary-tree-level-order-traversal/',
  },
  {
    id: 'tree_4',
    title: 'Validate Binary Search Tree',
    description: 'To validate a BST, why is "left < root AND root < right" check at each node NOT sufficient?',
    difficulty: 'medium',
    category: 'trees',
    gearReward: 'crystal_armor',
    timeLimit: 60,
    choices: { a: 'It is sufficient for all BST validation', b: 'It misses the global min/max constraint for each node', c: 'BST only checks parent-child relationship', d: 'You need to check sorted inorder traversal' },
    correctAnswer: 'b',
    explanation: 'Node in right subtree of root must be > root, not just > its direct parent. Pass min/max bounds down the recursion.',
    leetcodeUrl: 'https://leetcode.com/problems/validate-binary-search-tree/',
  },
  {
    id: 'tree_5',
    title: 'Lowest Common Ancestor',
    description: 'In BST with root=6, for nodes 2 and 8, the LCA is 6. For nodes 2 and 4, the LCA is?',
    difficulty: 'medium',
    category: 'trees',
    gearReward: 'crystal_armor',
    timeLimit: 45,
    choices: { a: '4', b: '2', c: '6', d: '3' },
    correctAnswer: 'b',
    explanation: 'In the BST [6,2,8,0,4,7,9], both 2 and 4 are in the left subtree. 4 is a descendant of 2. So LCA = 2.',
    leetcodeUrl: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/',
  },

  // ========== GRAPHS (gear: graph_crossbow, lava_shield, volcanic_boots, greedy_knife) ==========
  {
    id: 'graph_1',
    title: 'Number of Islands',
    description: 'Grid with "1"s (land) and "0"s (water). Islands = connected land components. Which algorithm counts them?',
    difficulty: 'medium',
    category: 'graphs',
    gearReward: 'graph_crossbow',
    timeLimit: 60,
    choices: { a: 'Dynamic programming on the grid', b: 'DFS/BFS from each unvisited "1", mark visited', c: 'Sort all cells and process in order', d: 'Binary search for boundary cells' },
    correctAnswer: 'b',
    explanation: 'For each "1" not yet visited, increment count and DFS/BFS to mark entire island as visited. O(m×n).',
    leetcodeUrl: 'https://leetcode.com/problems/number-of-islands/',
  },
  {
    id: 'graph_2',
    title: 'Clone Graph',
    description: 'Cloning a graph requires tracking already-cloned nodes. Why?',
    difficulty: 'medium',
    category: 'graphs',
    gearReward: 'graph_crossbow',
    timeLimit: 60,
    choices: { a: 'To save memory by sharing nodes', b: 'To avoid infinite loops in cyclic graphs', c: 'Graphs don\'t need tracking if undirected', d: 'To maintain the original node order' },
    correctAnswer: 'b',
    explanation: 'Without tracking visited nodes, cycles cause infinite recursion. HashMap<original, clone> breaks cycles.',
    leetcodeUrl: 'https://leetcode.com/problems/clone-graph/',
  },
  {
    id: 'graph_3',
    title: 'Course Schedule (Cycle Detection)',
    description: 'Can you finish [numCourses=2, prerequisites=[[1,0],[0,1]]]? What does this detect?',
    difficulty: 'medium',
    category: 'graphs',
    gearReward: 'lava_shield',
    timeLimit: 60,
    choices: { a: 'True — prerequisites are satisfiable', b: 'False — cycle detected in directed graph', c: 'True — BFS finds a valid order', d: 'False — too many prerequisites' },
    correctAnswer: 'b',
    explanation: '0 requires 1 AND 1 requires 0 creates a cycle. Topological sort (or DFS with 3-color marking) detects cycles.',
    leetcodeUrl: 'https://leetcode.com/problems/course-schedule/',
  },
  {
    id: 'graph_4',
    title: 'Pacific Atlantic Water Flow',
    description: 'Instead of checking each cell if it can reach both oceans (expensive), what\'s the efficient approach?',
    difficulty: 'medium',
    category: 'graphs',
    gearReward: 'volcanic_boots',
    timeLimit: 90,
    choices: { a: 'BFS from every cell checking all paths', b: 'Reverse: BFS from both ocean borders, find intersection', c: 'Dynamic programming on heights', d: 'Binary search on height values' },
    correctAnswer: 'b',
    explanation: 'BFS outward from Pacific border (top/left) and Atlantic border (bottom/right). Cells reachable from both = answer.',
    leetcodeUrl: 'https://leetcode.com/problems/pacific-atlantic-water-flow/',
  },
  {
    id: 'graph_5',
    title: 'Greedy Jump Game',
    description: 'Array [2,3,1,1,4]: can you reach the last index? Greedy keeps track of?',
    difficulty: 'medium',
    category: 'greedy',
    gearReward: 'greedy_knife',
    timeLimit: 45,
    choices: { a: 'Minimum steps to reach each index', b: 'Maximum reachable index at each step', c: 'Number of paths to last index', d: 'Previous jump length' },
    correctAnswer: 'b',
    explanation: 'Track maxReach. At each index i, if i <= maxReach, update maxReach = max(maxReach, i + nums[i]). If maxReach >= last, return true.',
    leetcodeUrl: 'https://leetcode.com/problems/jump-game/',
  },

  // ========== DYNAMIC PROGRAMMING (gear: dp_lance, sky_wings, memoize_helm) ==========
  {
    id: 'dp_1',
    title: 'Climbing Stairs',
    description: 'To climb n=5 stairs taking 1 or 2 steps at a time, how many distinct ways are there?',
    difficulty: 'easy',
    category: 'dp',
    gearReward: 'dp_lance',
    timeLimit: 45,
    choices: { a: '5', b: '6', c: '7', d: '8' },
    correctAnswer: 'd',
    explanation: 'dp[n] = dp[n-1] + dp[n-2]. dp[1]=1, dp[2]=2, dp[3]=3, dp[4]=5, dp[5]=8. Same as Fibonacci!',
    leetcodeUrl: 'https://leetcode.com/problems/climbing-stairs/',
  },
  {
    id: 'dp_2',
    title: 'House Robber',
    description: 'Houses [2,7,9,3,1], what\'s the max robbery without robbing adjacent houses?',
    difficulty: 'medium',
    category: 'dp',
    gearReward: 'dp_lance',
    timeLimit: 60,
    choices: { a: '11', b: '12', c: '13', d: '10' },
    correctAnswer: 'b',
    explanation: 'Rob houses 0,2,4: 2+9+1=12. dp[i] = max(dp[i-1], dp[i-2] + nums[i]). Result = 12.',
    leetcodeUrl: 'https://leetcode.com/problems/house-robber/',
  },
  {
    id: 'dp_3',
    title: 'Coin Change',
    description: 'Coins [1,5,11], amount=15. What\'s the minimum number of coins needed?',
    difficulty: 'medium',
    category: 'dp',
    gearReward: 'sky_wings',
    timeLimit: 60,
    choices: { a: '3 coins (5+5+5)', b: '2 coins (11+4) — invalid', c: '3 coins (11+1+1+1+1) = 5', d: '3 coins (5+5+5) = 15' },
    correctAnswer: 'a',
    explanation: '3 coins of 5 = 15. dp[i] = min coins to make i. Greedy fails (11+4 requires coin-4), DP handles all cases.',
    leetcodeUrl: 'https://leetcode.com/problems/coin-change/',
  },
  {
    id: 'dp_4',
    title: 'Longest Increasing Subsequence',
    description: 'For [10,9,2,5,3,7,101,18], the LIS length is 4. What\'s the DP recurrence?',
    difficulty: 'medium',
    category: 'dp',
    gearReward: 'memoize_helm',
    timeLimit: 75,
    choices: { a: 'dp[i] = dp[i-1] + 1 always', b: 'dp[i] = max(dp[j]+1) for all j<i where arr[j]<arr[i]', c: 'dp[i] = length of sorted unique subarray', d: 'dp[i] = max(dp[i-1], dp[i-2]+1)' },
    correctAnswer: 'b',
    explanation: 'For each i, find max dp[j]+1 for j<i where arr[j]<arr[i]. Answer is max(dp). O(n²), or O(n log n) with patience sort.',
    leetcodeUrl: 'https://leetcode.com/problems/longest-increasing-subsequence/',
  },
  {
    id: 'dp_5',
    title: 'Word Break',
    description: '"leetcode" with wordDict=["leet","code"] — can it be segmented? DP state dp[i] means?',
    difficulty: 'medium',
    category: 'dp',
    gearReward: 'memoize_helm',
    timeLimit: 75,
    choices: { a: 'dp[i] = number of ways to segment s[0..i]', b: 'dp[i] = true if s[0..i-1] can be segmented into words', c: 'dp[i] = last valid word ending at i', d: 'dp[i] = minimum words to cover s[0..i]' },
    correctAnswer: 'b',
    explanation: 'dp[i] = can we form s[0..i-1]. dp[0]=true. For i=1 to n: if dp[j] and s[j..i] in dict, dp[i]=true.',
    leetcodeUrl: 'https://leetcode.com/problems/word-break/',
  },

  // ========== BACKTRACKING (gear: backtrack_cloak) ==========
  {
    id: 'bt_1',
    title: 'Subsets',
    description: 'How many subsets does [1,2,3] have? Backtracking explores?',
    difficulty: 'medium',
    category: 'backtracking',
    gearReward: 'backtrack_cloak',
    timeLimit: 45,
    choices: { a: '6 subsets — pairs only', b: '7 subsets — exclude empty', c: '8 subsets — include empty set', d: '3 subsets — single elements only' },
    correctAnswer: 'c',
    explanation: 'For n elements: 2^n subsets. [],[1],[2],[3],[1,2],[1,3],[2,3],[1,2,3] = 8 subsets including empty set.',
    leetcodeUrl: 'https://leetcode.com/problems/subsets/',
  },
  {
    id: 'bt_2',
    title: 'Combination Sum',
    description: 'candidates=[2,3,6,7] target=7. Why can backtracking reuse elements in combinations?',
    difficulty: 'medium',
    category: 'backtracking',
    gearReward: 'backtrack_cloak',
    timeLimit: 60,
    choices: { a: 'It can\'t — each element is used once', b: 'The recursion continues from same index i (not i+1)', c: 'Backtracking naturally avoids duplicates', d: 'Elements are sorted to allow reuse' },
    correctAnswer: 'b',
    explanation: 'When recursing, pass same index i (not i+1) to allow reusing the current element. Pass i+1 for non-reuse.',
    leetcodeUrl: 'https://leetcode.com/problems/combination-sum/',
  },
  {
    id: 'bt_3',
    title: 'N-Queens Problem',
    description: 'For N=4, how many valid queen placements exist? The key constraint check is?',
    difficulty: 'hard',
    category: 'backtracking',
    gearReward: 'backtrack_cloak',
    timeLimit: 90,
    choices: { a: '2 solutions — check row, col, and both diagonals', b: '4 solutions — only check rows and columns', c: '8 solutions — only check column conflicts', d: '1 solution — uniquely determined' },
    correctAnswer: 'a',
    explanation: 'N=4 has 2 solutions. Use sets for column, positive diagonal (r-c), negative diagonal (r+c) to check attacks in O(1).',
    leetcodeUrl: 'https://leetcode.com/problems/n-queens/',
  },

  // ========== HEAPS (gear: cyber_gun) ==========
  {
    id: 'heap_1',
    title: 'Find Median from Data Stream',
    description: 'Two heaps approach: maxHeap (left half) and minHeap (right half). The median is?',
    difficulty: 'hard',
    category: 'heaps',
    gearReward: 'cyber_gun',
    timeLimit: 75,
    choices: { a: 'Average of all elements in both heaps', b: 'Top of maxHeap if odd total, else average of both tops', c: 'Always the top of minHeap', d: 'The element at index n/2' },
    correctAnswer: 'b',
    explanation: 'Keep sizes equal or maxHeap 1 larger. If odd: median = maxHeap.top(). If even: (maxHeap.top() + minHeap.top()) / 2.',
    leetcodeUrl: 'https://leetcode.com/problems/find-median-from-data-stream/',
  },
  {
    id: 'heap_2',
    title: 'K Closest Points to Origin',
    description: 'For points=[[1,3],[-2,2]], k=1: the closest point is [-2,2]. What heap and why?',
    difficulty: 'medium',
    category: 'heaps',
    gearReward: 'cyber_gun',
    timeLimit: 60,
    choices: { a: 'MinHeap of all distances, pop k times', b: 'MaxHeap of size k — pop when size > k', c: 'Sort all points by distance', d: 'Binary search on sorted distances' },
    correctAnswer: 'b',
    explanation: 'MaxHeap of size k: add point, if heap.size > k, pop the farthest. After all points, heap contains k closest. O(n log k).',
    leetcodeUrl: 'https://leetcode.com/problems/k-closest-points-to-origin/',
  },

  // ========== TRIES (gear: trie_rifle) ==========
  {
    id: 'trie_1',
    title: 'Implement Trie',
    description: 'A Trie node for lowercase letters needs? What\'s the space per node?',
    difficulty: 'medium',
    category: 'tries',
    gearReward: 'trie_rifle',
    timeLimit: 60,
    choices: { a: 'Array of 26 TrieNode pointers + isEndOfWord boolean', b: 'HashMap<char, TrieNode> + isEndOfWord', c: 'Both A and B are valid — tradeoff is time vs space', d: 'Linked list of characters' },
    correctAnswer: 'c',
    explanation: 'Array[26] is O(26) per node but faster lookup. HashMap is sparse but slower. Both are valid Trie implementations.',
    leetcodeUrl: 'https://leetcode.com/problems/implement-trie-prefix-tree/',
  },
  {
    id: 'trie_2',
    title: 'Word Search II',
    description: 'Find all words from a dictionary in a 2D board. Why is Trie better than HashSet for dictionary lookup?',
    difficulty: 'hard',
    category: 'tries',
    gearReward: 'trie_rifle',
    timeLimit: 90,
    choices: { a: 'Trie is faster for exact match lookups', b: 'Trie allows early termination when no word starts with current prefix', c: 'HashSet has higher space complexity', d: 'Trie can store words of any length' },
    correctAnswer: 'b',
    explanation: 'When DFS explores a path with no matching prefix in Trie, we can immediately backtrack. HashSet requires full word to check.',
    leetcodeUrl: 'https://leetcode.com/problems/word-search-ii/',
  },

  // ========== BIT MANIPULATION (gear: void_armor) ==========
  {
    id: 'bit_1',
    title: 'Single Number',
    description: 'Array [4,1,2,1,2] has one element appearing once. XOR trick works because?',
    difficulty: 'easy',
    category: 'bitmanipulation',
    gearReward: 'void_armor',
    timeLimit: 45,
    choices: { a: 'XOR of a number with itself = 0, XOR with 0 = itself', b: 'XOR sums all bits without carry', c: 'Duplicate numbers cancel in binary', d: 'XOR is always commutative but not associative' },
    correctAnswer: 'a',
    explanation: 'a XOR a = 0, a XOR 0 = a. XOR all elements: duplicates cancel, leaving only the single number. 4 XOR 1 XOR 2 XOR 1 XOR 2 = 4.',
    leetcodeUrl: 'https://leetcode.com/problems/single-number/',
  },
  {
    id: 'bit_2',
    title: 'Number of 1 Bits',
    description: 'Hamming weight of 11 (binary: 1011). n & (n-1) removes?',
    difficulty: 'easy',
    category: 'bitmanipulation',
    gearReward: 'void_armor',
    timeLimit: 45,
    choices: { a: 'The rightmost 0 bit', b: 'The leftmost 1 bit', c: 'The rightmost 1 bit', d: 'All bits to the right of MSB' },
    correctAnswer: 'c',
    explanation: 'n & (n-1) clears the rightmost set (1) bit. For 1011: 1011 & 1010 = 1010. Count how many times until n=0.',
    leetcodeUrl: 'https://leetcode.com/problems/number-of-1-bits/',
  },
]

export const getQuestionById = (id: string): Question | undefined =>
  QUESTIONS.find(q => q.id === id)

export const getQuestionByGearReward = (gearId: string): Question | undefined =>
  QUESTIONS.find(q => q.gearReward === gearId)

export const getQuestionsByCategory = (category: string): Question[] =>
  QUESTIONS.filter(q => q.category === category)

export const getQuestionsByDifficulty = (difficulty: string): Question[] =>
  QUESTIONS.filter(q => q.difficulty === difficulty)
